name: wordwolf
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+2

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  go_router: ^8.0.1
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^2.1.1
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  retrofit: ^4.0.1
  dio: ^5.2.1
  json_annotation: ^4.8.1
  uuid: ^3.0.7
  share_plus: ^7.0.2
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  riverpod_generator: ^2.2.3
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1

flutter:

  uses-material-design: true
