// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-VrYqmBtRO-1Yo1C7EDZBlFIkbszcMhk',
    appId: '1:1019371604114:android:91694d7b0ed35621123e4b',
    messagingSenderId: '1019371604114',
    projectId: 'pocket-schedule-1dab1',
    storageBucket: 'pocket-schedule-1dab1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa0UluwBKb-imf4fFRkwD99zgDgH5qObQ',
    appId: '1:1019371604114:ios:ad7b17151fbc06b6123e4b',
    messagingSenderId: '1019371604114',
    projectId: 'pocket-schedule-1dab1',
    storageBucket: 'pocket-schedule-1dab1.appspot.com',
    androidClientId: '1019371604114-blafkb5rvl440k18uo1i5b8990qkvq89.apps.googleusercontent.com',
    iosClientId: '1019371604114-gut35qose36srsec0b0ct1n5o8tfknkr.apps.googleusercontent.com',
    iosBundleId: 'com.pocket.schedule',
  );
}
